spring:
  application:
    name: doodle-scheduler-hexagonal
  datasource:
    url:
    username:
    password:
    driver-class-name:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect:
        format_sql:
        use_sql_comments:
    show-sql:
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

springdoc:
  api-docs:
    path: /v1/api-docs
    enabled: false
  swagger-ui:
    path: /swagger-ui.html
    enabled: false
    operations-sorter: method
  show-actuator: false
